#pragma leco add_include_dir "MBROLA/Misc"
#pragma leco add_include_dir "MBROLA/Parser"
#pragma leco add_include_dir "MBROLA/Database"
#pragma leco add_include_dir "MBROLA/Engine"

#define LIBRARY

#include "MBROLA/Misc/common.h"
#include "MBROLA/Misc/vp_error.h"
#include "MBROLA/Misc/mbralloc.h"
#include "MBROLA/Misc/incdll.h"
#include "MBROLA/Parser/phone.h"
#include "MBROLA/Database/diphone_info.h"
#include "MBROLA/Engine/diphone.h"
#include "MBROLA/Engine/mbrola.h"
#include "MBROLA/Database/database.h"
#include "MBROLA/Database/database_old.h"
#include "MBROLA/Misc/audio.h"
#include "MBROLA/Parser/parser.h"
#include "MBROLA/Parser/parser_input.h"
#include "MBROLA/Database/hash_tab.h"
#include "MBROLA/LibOneChannel/onechannel.h"

#include "MBROLA/Misc/mbralloc.c"
#include "MBROLA/Database/little_big.c"
#include "MBROLA/Misc/common.c"
#include "MBROLA/Parser/phone.c"
#include "MBROLA/Engine/diphone.c"
#include "MBROLA/Misc/g711.c"
#include "MBROLA/Misc/audio.c"
#include "MBROLA/Engine/mbrola.c"
#include "MBROLA/Database/diphone_info.c"
#include "MBROLA/Database/database_old.c"
#include "MBROLA/Database/database.c"
#include "MBROLA/Database/zstring_list.c"
#include "MBROLA/Parser/phonbuff.c"
#include "MBROLA/Parser/fifo.c"
#include "MBROLA/Parser/parser_input.c"
#include "MBROLA/Parser/input_file.c"
#include "MBROLA/Database/hash_tab.c"
#include "MBROLA/Misc/vp_error.c"
